import Head from "next/head";
import styles from "@/styles/Home.module.css";
import About from "@/components/About";
import Cover from "@/components/Cover";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Products from "@/components/Products";

export default function Home() {
  return (
    <>
      <Head>
        <title>Otica Vida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section>
        <Cover/>
        <About/>
        <Products/>
      </section>
      <Footer/>
    </>
  );
}
